// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { Card as __Card } from "./card_type";
import { DrawStatus as __DrawStatus } from "./draw_status_type";

export type Draw = {
  id: bigint,
  turnId: bigint,
  attacker: Identity,
  attackingCard: __Card,
  defendingCard: __Card | undefined,
  status: __DrawStatus,
  createdAt: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Draw {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU64Type()),
      new ProductTypeElement("turnId", AlgebraicType.createU64Type()),
      new ProductTypeElement("attacker", AlgebraicType.createIdentityType()),
      new ProductTypeElement("attackingCard", __Card.getTypeScriptAlgebraicType()),
      new ProductTypeElement("defendingCard", AlgebraicType.createOptionType(__Card.getTypeScriptAlgebraicType())),
      new ProductTypeElement("status", __DrawStatus.getTypeScriptAlgebraicType()),
      new ProductTypeElement("createdAt", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Draw): void {
    Draw.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Draw {
    return Draw.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


