// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { RoundStatus as __RoundStatus } from "./round_status_type";

export type Round = {
  id: bigint,
  gameId: bigint,
  roundNumber: number,
  status: __RoundStatus,
  loser: Identity | undefined,
  startedAt: Timestamp,
  finishedAt: Timestamp | undefined,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Round {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU64Type()),
      new ProductTypeElement("gameId", AlgebraicType.createU64Type()),
      new ProductTypeElement("roundNumber", AlgebraicType.createU32Type()),
      new ProductTypeElement("status", __RoundStatus.getTypeScriptAlgebraicType()),
      new ProductTypeElement("loser", AlgebraicType.createOptionType(AlgebraicType.createIdentityType())),
      new ProductTypeElement("startedAt", AlgebraicType.createTimestampType()),
      new ProductTypeElement("finishedAt", AlgebraicType.createOptionType(AlgebraicType.createTimestampType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Round): void {
    Round.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Round {
    return Round.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


