// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { TurnStatus as __TurnStatus } from "./turn_status_type";

export type Turn = {
  id: bigint,
  roundId: bigint,
  turnNumber: number,
  attacker: Identity,
  defender: Identity,
  status: __TurnStatus,
  startedAt: Timestamp,
  finishedAt: Timestamp | undefined,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Turn {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU64Type()),
      new ProductTypeElement("roundId", AlgebraicType.createU64Type()),
      new ProductTypeElement("turnNumber", AlgebraicType.createU32Type()),
      new ProductTypeElement("attacker", AlgebraicType.createIdentityType()),
      new ProductTypeElement("defender", AlgebraicType.createIdentityType()),
      new ProductTypeElement("status", __TurnStatus.getTypeScriptAlgebraicType()),
      new ProductTypeElement("startedAt", AlgebraicType.createTimestampType()),
      new ProductTypeElement("finishedAt", AlgebraicType.createOptionType(AlgebraicType.createTimestampType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Turn): void {
    Turn.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Turn {
    return Turn.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


