// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

import { DeckSize as __DeckSize } from "./deck_size_type";

export type UpdateGameSettings = {
  lobbyId: bigint,
  deckSize: __DeckSize,
  startingCards: number,
  maxAttackCards: number,
  multiRoundMode: boolean,
  maxPoints: number,
  anyoneCanAttack: boolean,
  trumpCardToPlayer: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace UpdateGameSettings {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("lobbyId", AlgebraicType.createU64Type()),
      new ProductTypeElement("deckSize", __DeckSize.getTypeScriptAlgebraicType()),
      new ProductTypeElement("startingCards", AlgebraicType.createU8Type()),
      new ProductTypeElement("maxAttackCards", AlgebraicType.createU8Type()),
      new ProductTypeElement("multiRoundMode", AlgebraicType.createBoolType()),
      new ProductTypeElement("maxPoints", AlgebraicType.createU8Type()),
      new ProductTypeElement("anyoneCanAttack", AlgebraicType.createBoolType()),
      new ProductTypeElement("trumpCardToPlayer", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: UpdateGameSettings): void {
    UpdateGameSettings.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): UpdateGameSettings {
    return UpdateGameSettings.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

