version: "3"

services:
  jot:
    image: jot:latest
    container_name: jot
    restart: unless-stopped
    command: ["npm", "start", "--production"]
    volumes:
      - ./data:/app/data
    environment:
      - TELEGRAM_BOT_TOKEN=0000000:aaaaaaaeeeeeeeeeeee
      - BOT_ADMIN_ID=000000000
      - INBOX_PATH=messages
      - FILENAME_TEMPLATE=inbox_20060102_150405.md
